services:
    - type: cron
      name: fractal-favorites-cron
      runtime: node
      plan: starter
      schedule: "0 12 * * *"
      region: oregon
      buildCommand: "bun install"
      startCommand: bash worker.sh
